### ISSUE TITLE
Time to switch to GitHub Actions?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/FastGaussQuadrature.jl#92]
What is up with this message?
<img width="1324" alt="Screen Shot 2021-01-11 at 9 57 25 AM" src="https://user-images.githubusercontent.com/8176037/104204982-79c45380-53f3-11eb-90a5-fee4d9820d50.png">

**Comment by dlfivefifty** [comment]
no idea, all the links error out.

Probably we should move CI to Github actions but I don't know how to do that. (GitHub actions have the annoying feature that they aren't version controlled.. shocking!)

**Comment by dlfivefifty** [comment]
I don't know why we even switch to travis.com since travis.org is still working..

**Comment by hyrodium** [comment]
In my repository, migrating travis.org to travis.org was easy (just clicking some buttons), so I don't know why the tests are not running...

**Comment by hyrodium** [comment]
Taking this opportunity, I'm trying to switch Travis to GitHub Actions in [my repository](https://github.com/hyrodium/BasicBSpline.jl) for an experiment.

I succeeded to enable GitHub Actions, but, I couldn't figure out how to disable the checks for travis.

![image](https://user-images.githubusercontent.com/7488140/104301209-b6cf3980-550a-11eb-87e9-a57f200d26f7.png)

Do you have any ideas?

**Comment by hyrodium** [comment]
Ah, I found it!

`Settings` -> `Branches` -> `Branch protection rules` -> `Edit`
![image](https://user-images.githubusercontent.com/7488140/104309007-d4a19c00-5514-11eb-9cf1-d0a12af00edc.png)

So, I can help this issue.

**Comment by hyrodium** [comment]
Here's an instruction.

## 1. Configure repository on GitHub
Generate keys by DocumenterTools.jl
```julia
julia> using DocumenterTools

julia> Travis.genkeys(user="JuliaApproximation", repo="git@github.com:JuliaApproximation/FastGaussQuadrature.git")

<keys will be generated here.>
```

### Add Deploy keys
add Deploy key which begin `ssh-rsa`.

example:
![](https://i.imgur.com/yTPbIB5.png)


### Add Secret key
add Secret key which which is longer than deploy key.

example:
![](https://i.imgur.com/KcevhkB.png)


## 2. Update code in the repository
### Add `.github/workflows/ci.yml`
To install github actions, add some YAML files in `.github/workflows`.
In this case, we just need `.github/workflows/ci.yml`.

```yml
name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.3'
          - '1.5'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: doctest
            using FastGaussQuadrature
            doctest(FastGaussQuadrature)'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
```

This `ci.yml` file is generated by `PkgTemplates.jl`.

### Update badge in README.md

```
[![Build Status](https://github.com/JuliaApproximation/FastGaussQuadrature.jl/workflows/CI/badge.svg)](https://github.com/JuliaApproximation/FastGaussQuadrature.jl/actions)
```

## 3. Remove Travis
* On Travis
    * Disable FastGaussQuadrature.jl
* Settings -> Branches -> Branch protection rules -> Edit
    * remove travis from branch protection rules
